services:
  es_server:
    image: engelsystem:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_TYPE: mariadb
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
      APP_URL: /
    ports:
      - "8080:80"
    env_file: deployment.env
    networks:
      - database
      - internet
    depends_on:
      es_database:
        condition: service_healthy
  es_database:
    image: mariadb:10.7
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
        timeout: 20s
        retries: 10
volumes:
  db: {}

networks:
  database:
    internal: true
  internet:

